---
- name: Deploy Flask app
  hosts: all
  become: yes
  tasks:
    - name: Install Python3 and pip
      yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask dependencies
      pip:
        name: 
          - Flask
          - psycopg2  # PostgreSQL adapter for Flask

    - name: Clone Flask app repository
      git:
        repo: 'https://github.com/your-flask-app-repo.git'
        dest: /var/www/flask-app
        version: "{{ version_tag }}"

    - name: Configure environment variables for Flask
      template:
        src: "flask.env.j2"
        dest: "/var/www/flask-app/.env"

    - name: Set up Flask app to run with systemd
      template:
        src: "flask-app.service.j2"
        dest: "/etc/systemd/system/flask-app.service"

    - name: Start Flask app service
      systemd:
        name: flask-app
        state: started
        enabled: true