---
- name: Set up PostgreSQL database
  hosts: all
  become: yes
  tasks:
    - name: Install PostgreSQL
      yum:
        name: postgresql-server
        state: present

    - name: Initialize PostgreSQL database
      command: postgresql-setup initdb

    - name: Start PostgreSQL service
      service:
        name: postgresql
        state: started
        enabled: true

    - name: Create PostgreSQL database
      postgresql_db:
        name: shared_db
        state: present

    - name: Create user for Flask and Node.js apps
      postgresql_user:
        name: app_user
        password: "{{ db_password }}"
        db: shared_db
        priv: "ALL"
        state: present

    - name: Create the necessary schema
      postgresql_query:
        db: shared_db
        query: "CREATE SCHEMA IF NOT EXISTS shared_schema;"