---
- name: Create Flask app directory
  file:
    path: /var/www/flask-app
    state: directory
    owner: ec2-user
    group: ec2-user
- name: Copy Flask app files
  copy:
    src: "{{ flask_app_source }}"
    dest: /var/www/flask-app
    remote_src: yes
- name: Install Flask dependencies
  pip:
    requirements: /var/www/flask-app/requirements.txt
    virtualenv: /var/www/flask-app/venv
    virtualenv_command: python3 -m venv
- name: Deploy Flask systemd service
  template:
    src: flask-app.service.j2
    dest: /etc/systemd/system/flask-app.service
  notify: Restart Flask app
- name: Start and enable Flask app
  systemd:
    name: flask-app
    state: started
    enabled: yes