---
- name: Install PostgreSQL 
  package:
    name: postgresql
    state: present
  when: ansible_distribution == "CentOS"
- name: Install PostgreSQL (Debian)
  apt:
    name: postgresql
    update_cache: yes
  when: ansible_os_family == "Debian"
- name: Initialize PostgreSQL database
  command: postgresql-setup initdb
- name: Start and enable PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: yes
- name: Run init.sql script
  become: yes
  become_user: postgres
  shell: psql -f /path/to/init.sql