---
- name: Configure the PostgreSQL RPM repository
  yum:
   name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-10-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
   state: present

- name: Install PostgreSQL 
  package:
    name: postgresql
    state: present
  when: ansible_distribution == "Amazon linux"

- name: Install PostgreSQL (Debian)
  apt:
    name: postgresql
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: check if database is initialized
  stat:
   path: /var/lib/pgsql/14/data/pg_hba.conf
   register: result
- name: Initialize the database
  shell: /usr/pgsql-14/bin/postgresql-14-setup initdb
  when: not result.stat.exists
- name: Start and enable PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: yes
